### ISSUE TITLE
Read the google docs directly to get financial data

### ISSUE THREAD

**Issue by kvarak** [verifa/metrics#148]
Today we need to manually update the json file in the config based on the google sheet with the financial information. It would be good if we could just take the information directly from here: https://docs.google.com/spreadsheets/d/1o54u9Z3itVevBT_jb7KFnPcOAtDOG8qemdho-5TIMf0/edit?usp=sharing

Maybe this helps: https://data-flair.training/blogs/read-data-from-google-sheets-using-python/

**Comment by praqma-thi** [comment]
Just noting that I enabled the Google Sheets API for our `verifa-metrics` project in the cloud console

**Comment by praqma-thi** [comment]
@lolpatrol 
I pushed a draft to [`148-parse-sheets`](https://github.com/verifa/metrics/tree/148-parse-sheets).
You'll find it under `routes/`, has a main function to do some fiddling with it.
Credentials are in [Google Cloud Console](console.cloud.google.com/) (ours are `verifa-metrics/verifa-metrics-gsheets`).

**Comment by praqma-thi** [comment]
Tidied up the [148-parse-sheets](https://github.com/verifa/metrics/tree/148-parse-sheets)  draft.
Removed the credentials, replaced it with a service account.
Shared our sample sheet with the service account, looks to be working just fine.

**Comment by kvarak** [comment]
Not needed anymore as the numbers have been moved to Notion.
