### ISSUE TITLE
Move financial data to Notion instead of adding feature to read Google Sheet

### ISSUE THREAD

**Issue by kvarak** [verifa/metrics#176]
I believe that Notion is a better place to put information in, so instead of us adding the functionality to read a google sheet. I think it's better to add the data to Notion. 

Definition of done:
- Move financial data to Notion
- Read notion instead of tempo config to get the costs and income
- Remove costs and income from tempo-config

**Comment by kvarak** [comment]
Note: doing this will make #148 not needed.

**Comment by lolpatrol** [comment]
- [x] Move financial data to Notion
- [x] Read notion instead of tempo config to get the costs and income
- [ ] Remove costs and income from tempo-config (Fix in tempo-config)
